export const C = {
  bg: 'var(--bg)',
  surface: 'var(--surface)',
  surface2: 'var(--surface2)',
  surface3: 'var(--surface3)',
  blurple: 'var(--blurple)',
  blurpleHov: 'var(--blurple-hover)',
  blurpleDim: 'var(--blurple-dim)',
  green: 'var(--green)',
  greenDim: 'var(--green-dim)',
  red: 'var(--red)',
  yellow: 'var(--yellow)',
  text: 'var(--text)',
  muted: 'var(--muted)',
  faint: 'var(--faint)',
  border: 'var(--border)',
  white: 'var(--white)',
};

export const ALL_TAGS = [
  'moderation',
  'admin',
  'automod',
  'antispam',
  'logging',
  'moderation-logging',
  'roles',
  'permissions',
  'tickets',
  'modmail',
  'welcome',
  'goodbye',
  'fun',
  'memes',
  'image',
  'image-generation',
  'meme-generator',
  'music',
  'dj',
  'audio',
  'voice',
  'playback',
  'economy',
  'shop',
  'currency',
  'games',
  'minigames',
  'pvp',
  'social',
  'polls',
  'surveys',
  'utility',
  'info',
  'stats',
  'analytics',
  'ai',
  'nlp',
  'translation',
  'search',
  'webhook',
  'embed',
  'developer-tools',
  'testing',
  'backup',
  'restore',
  'scheduler',
  'reminders',
  'events',
  'giveaway',
  'premium',
  'payments',
  'security',
  'encryption',
  'oauth',
  'integration',
  'youtube',
  'twitch',
  'spotify',
  'localization',
  'i18n',
  'emoji',
  'leveling',
  'leaderboard',
  'moderation-tools',
  'developer',
  'ui',
  'ux',
  'performance',
  'cache',
  'database',
  'sync',
  'import',
  'export',
  'web-apis',
  'bots',
  'community',
  'support',
  'education',
  'productivity',
  'custom',
];

export const FRAMEWORKS = [
  'Discord.js',
  'Discord.py',
  'Discordeno',
  'eris',
  'discord-io',
  'JDA',
  'Javacord',
  'discord4j',
  'DSharpPlus',
  'Discord.Net',
  'DisCatSharp',
  'serenity',
  'twilight',
  'discordgo',
  'discord.rb',
  'Nyxx',
  'Framework-agnostic JSON',
  'Custom',
];

export const BOT_TOOLS = [
  'Discord Bot Maker',
  'Discord Bot Builder',
  'Bot Maker For Discord',
  'Bot Studio For Discord',
  'Discord Bot Engine',
  'Discord Bot Factory',
  'Discord Bot Workshop',
];

export const CMD_TYPES = ['Slash', 'Context', 'Message'];

export const FW_COLORS = {
  'Discord.js': { bg: 'rgba(59,165,92,0.15)', color: '#3ba55c' },
  'Discord.py': { bg: 'rgba(88,101,242,0.15)', color: '#5865F2' },
  Discordeno: { bg: 'rgba(254,163,0,0.15)', color: '#fea300' },
  eris: { bg: 'rgba(59,165,92,0.15)', color: '#3ba55c' },
  'discord-io': { bg: 'rgba(59,165,92,0.15)', color: '#3ba55c' },
  JDA: { bg: 'rgba(244,67,54,0.15)', color: '#f44236' },
  Javacord: { bg: 'rgba(244,67,54,0.15)', color: '#f44236' },
  discord4j: { bg: 'rgba(244,67,54,0.15)', color: '#f44236' },
  DSharpPlus: { bg: 'rgba(107,114,128,0.15)', color: '#6b7280' },
  'Discord.Net': { bg: 'rgba(107,114,128,0.15)', color: '#6b7280' },
  DisCatSharp: { bg: 'rgba(107,114,128,0.15)', color: '#6b7280' },
  serenity: { bg: 'rgba(206,85,70,0.15)', color: '#ce5546' },
  twilight: { bg: 'rgba(206,85,70,0.15)', color: '#ce5546' },
  discordgo: { bg: 'rgba(0,173,239,0.15)', color: '#00aded' },
  'discord.rb': { bg: 'rgba(204,52,51,0.15)', color: '#cc3433' },
  Nyxx: { bg: 'rgba(0,173,223,0.15)', color: '#00addf' },
  'Framework-agnostic JSON': { bg: 'rgba(149,55,255,0.15)', color: '#9537ff' },
  Custom: { bg: 'rgba(255,255,255,0.08)', color: '#DBDEE1' },
  'Discord Bot Maker': { bg: 'rgba(237,66,69,0.15)', color: '#ED4245' },
  'Discord Bot Builder': { bg: 'rgba(237,66,69,0.15)', color: '#ED4245' },
  'Bot Maker For Discord': { bg: 'rgba(237,66,69,0.15)', color: '#ED4245' },
  'Bot Studio For Discord': { bg: 'rgba(237,66,69,0.15)', color: '#ED4245' },
  'Discord Bot Engine': { bg: 'rgba(237,66,69,0.15)', color: '#ED4245' },
  'Discord Bot Factory': { bg: 'rgba(237,66,69,0.15)', color: '#ED4245' },
  'Discord Bot Workshop': { bg: 'rgba(237,66,69,0.15)', color: '#ED4245' },
};

export const TYPE_COLORS = { Slash: C.blurple, Context: C.green, Message: C.yellow };

export const MOCK_USER = { id: '123456789', username: 'Kai', avatar: null };

export const fmt = (n) => (n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n));
